import numpy as np, math, json, time, argparse
from scipy.special import poch

parser=argparse.ArgumentParser()
parser.add_argument('--case', required=True)
parser.add_argument('--rep', type=int, required=True)
parser.add_argument('--out', required=True)
args=parser.parse_args()

CASES={
 'couette': dict(TL=1.0,TR=1.0,UL=-1.0,UR=1.0),
 'fourier': dict(TL=0.70,TR=1.40,UL=0.0,UR=0.0),
 'combined': dict(TL=0.75,TR=1.35,UL=-1.0,UR=1.0),
 'strong': dict(TL=0.60,TR=1.60,UL=-1.50,UR=1.50),
}
if args.case not in CASES: raise SystemExit('unknown case')
pars=CASES[args.case]

L=1.0; NC=20; NP=10000; DT=0.002; KN_TARGET=0.12; DIAM=1.0
SIGMA_T=math.pi*DIAM**2
N0=1.0/(math.sqrt(2)*SIGMA_T*KN_TARGET); WEIGHT=N0*L/NP; VCELL=L/NC
GMAJ=16.0; BURN=3500; SAMPLE_STEPS=6500; SNAP_STRIDE=50
TL,TR,UL,UR=pars['TL'],pars['TR'],pars['UL'],pars['UR']
SEED=2026091200 + 100*list(CASES).index(args.case)+args.rep
SAMPLE_CELLS=[3,6,10,13,16]  # y/L = .175,.325,.525,.675,.825
MAX_HERM=8; WEAK_PAIRS=2500; BLOCK=250
rng=np.random.default_rng(SEED)

# --- Hermite/Fock reconstruction generated by Xi ---
def multiindices(N):
    return [(a,b,c) for a in range(N+1) for b in range(N+1-a) for c in range(N+1-a-b)]
MIS=multiindices(MAX_HERM)
def mfact(nu): return math.factorial(nu[0])*math.factorial(nu[1])*math.factorial(nu[2])
def afact(a): return math.factorial(a[0])*math.factorial(a[1])*math.factorial(a[2])
SQFAC={nu:math.sqrt(mfact(nu)) for nu in MIS}; DEG={nu:sum(nu) for nu in MIS}; IDX={nu:i for i,nu in enumerate(MIS)}

def hermite_coeffs(x):
    m=len(x); H=[]
    for j in range(3):
        h=np.empty((MAX_HERM+1,m)); h[0]=1.; h[1]=x[:,j]
        for n in range(1,MAX_HERM): h[n+1]=x[:,j]*h[n]-n*h[n-1]
        H.append(h)
    return np.array([float(np.mean(H[0][nu[0]]*H[1][nu[1]]*H[2][nu[2]])/SQFAC[nu]) for nu in MIS])

def F_coeffs(N):
    mats={}; C=-(32/5)*math.sqrt(math.pi)*DIAM**2
    for k in range((2*N-2)//2+1):
        ck=C*float(poch(-.5,k)/poch(3.5,k))*(-1.)**k/math.factorial(k)/4.**k
        for p in range(k+1):
            for q in range(k+1-p):
                r=k-p-q; base=(2*p,2*q,2*r)
                amp=ck*math.factorial(k)/(math.factorial(p)*math.factorial(q)*math.factorial(r))
                for i in range(3):
                    for j in range(3):
                        a=list(base); a[i]+=1; a[j]+=1; a=tuple(a)
                        mats.setdefault(a,np.zeros((3,3))); mats[a][i,j]+=amp/4
                for h in range(3):
                    a=list(base); a[h]+=2; a=tuple(a)
                    mats.setdefault(a,np.zeros((3,3)))
                    for i in range(3): mats[a][i,i]-=amp/12
    return mats
FCO={N:F_coeffs(N) for N in range(2,MAX_HERM+1)}

# Precompute the Xi-generated bilinear collision tensors once at the maximum order.
# Coefficients of a fixed multiindex pair are independent of the later cumulative
# Hermite cutoff N, so lower-order reconstructions are obtained by masking.
M=len(MIS); FMAX=FCO[MAX_HERM]
PT=np.zeros((M,M,3,3)); QT=np.zeros((M,M,3))
for ii,nu in enumerate(MIS):
    for jj,lam in enumerate(MIS):
        alpha=(nu[0]+lam[0],nu[1]+lam[1],nu[2]+lam[2]); fm=FMAX.get(alpha)
        if fm is not None:
            PT[ii,jj]=((-1.)**DEG[lam])*afact(alpha)/(SQFAC[nu]*SQFAC[lam])*fm
        sqrtprod=SQFAC[nu]*SQFAC[lam]
        qv=np.zeros(3)
        for j in range(3):
            if nu[j]>0:
                aa=[nu[0]+lam[0],nu[1]+lam[1],nu[2]+lam[2]]; aa[j]-=1; aa=tuple(aa); fm=FMAX.get(aa)
                if fm is not None:
                    nue=list(nu); nue[j]-=1; nue=tuple(nue)
                    qv += .5*afact(aa)*(-1.)**DEG[lam]*sqrtprod/(mfact(nue)*mfact(lam))*fm[:,j]
            if lam[j]>0:
                aa=[nu[0]+lam[0],nu[1]+lam[1],nu[2]+lam[2]]; aa[j]-=1; aa=tuple(aa); fm=FMAX.get(aa)
                if fm is not None:
                    lae=list(lam); lae[j]-=1; lae=tuple(lae)
                    qv += .5*afact(aa)*(-1.)**(DEG[lam]-1)*sqrtprod/(mfact(nu)*mfact(lae))*fm[:,j]
        QT[ii,jj]=qv

def reconstruct_weighted(N,W,heat=False):
    mask=np.array([DEG[nu]<=N for nu in MIS])
    inds=np.where(mask)[0]
    Ws=W[np.ix_(inds,inds)]
    if not heat:
        Ps=PT[np.ix_(inds,inds)]
        return np.einsum('ab,abij->ij',Ws,Ps,optimize=True)
    Qs=QT[np.ix_(inds,inds)]
    return np.einsum('ab,abi->i',Ws,Qs,optimize=True)

# --- physical DSMC ---
def wall_emit(n,T,Ux,sign):
    vv=np.empty((n,3)); vv[:,0]=Ux+math.sqrt(T)*rng.normal(size=n); vv[:,2]=math.sqrt(T)*rng.normal(size=n)
    vv[:,1]=sign*np.sqrt(-2*T*np.log(np.maximum(rng.random(n),1e-15))); return vv

def walls(yold,vold,ynew,vnew):
    m=ynew<0
    if np.any(m):
        ids=np.where(m)[0]; th=yold[ids]/np.maximum(-vold[ids,1],1e-15); rem=np.clip(DT-th,0,DT); ve=wall_emit(len(ids),TL,UL,1)
        vnew[ids]=ve; ynew[ids]=ve[:,1]*rem
    m=ynew>L
    if np.any(m):
        ids=np.where(m)[0]; th=(L-yold[ids])/np.maximum(vold[ids,1],1e-15); rem=np.clip(DT-th,0,DT); ve=wall_emit(len(ids),TR,UR,-1)
        vnew[ids]=ve; ynew[ids]=L+ve[:,1]*rem
    np.clip(ynew,0,L-1e-14,out=ynew)

y=rng.random(NP)*L; v=rng.normal(size=(NP,3))
nsamp=len(SAMPLE_CELLS); cell_to_k={c:k for k,c in enumerate(SAMPLE_CELLS)}
# event totals and block totals per sampled cell
S_event=np.zeros((nsamp,3,3)); H_event=np.zeros((nsamp,3)); n_event=np.zeros(nsamp,int)
nb=(SAMPLE_STEPS+BLOCK-1)//BLOCK
Sb=np.zeros((nsamp,nb,3,3)); Hb=np.zeros((nsamp,nb,3)); Cb=np.zeros((nsamp,nb),int)
# snapshot data per sampled cell
snap_a=[[] for _ in range(nsamp)]; snap_n=[[] for _ in range(nsamp)]; snap_T=[[] for _ in range(nsamp)]
weakS=[[] for _ in range(nsamp)]; weakH=[[] for _ in range(nsamp)]
# profiles
prof_n=np.zeros(NC); prof_u=np.zeros((NC,3)); prof_t=np.zeros(NC); prof_ct=np.zeros(NC)
max_g_seen=0.0; majorant_hits=0
start=time.time(); total=BURN+SAMPLE_STEPS
for step in range(total):
    yo=y.copy(); vo=v.copy(); y += v[:,1]*DT; walls(yo,vo,y,v)
    cells=np.minimum((y/VCELL).astype(int),NC-1)

    if step>=BURN and (step-BURN)%SNAP_STRIDE==0:
        # global profiles
        for c in range(NC):
            idx=np.where(cells==c)[0]
            if len(idx)<8: continue
            U=v[idx].mean(0); C=v[idx]-U; T=np.mean(np.sum(C*C,axis=1))/3; n=WEIGHT*len(idx)/VCELL
            prof_n[c]+=n; prof_u[c]+=U; prof_t[c]+=T; prof_ct[c]+=1
        # sampled cell data
        for kk,c in enumerate(SAMPLE_CELLS):
            idx=np.where(cells==c)[0]
            if len(idx)<20: continue
            U=v[idx].mean(0); C=v[idx]-U; T=np.mean(np.sum(C*C,axis=1))/3; n=WEIGHT*len(idx)/VCELL
            snap_a[kk].append(hermite_coeffs(C/math.sqrt(T))); snap_n[kk].append(n); snap_T[kk].append(T)
            mp=WEAK_PAIRS
            ia=rng.choice(idx,size=mp,replace=True); ib=rng.choice(idx,size=mp,replace=True)
            eq=(ia==ib)
            while np.any(eq):
                ib[eq]=rng.choice(idx,size=np.count_nonzero(eq),replace=True); eq=(ia==ib)
            va=v[ia]; vb=v[ib]; g=va-vb; gn=np.linalg.norm(g,axis=1)
            gg=g[:,:,None]*g[:,None,:]; tr=np.sum(g*g,axis=1); gstf=gg-np.eye(3)[None,:,:]*(tr[:,None,None]/3)
            weakS[kk].append(-(math.pi*DIAM**2/4)*n*n*np.mean(gn[:,None,None]*gstf,axis=0))
            Vr=.5*(va+vb)-U
            weakH[kk].append(-(math.pi*DIAM**2/4)*n*n*np.mean(gn[:,None]*np.einsum('nj,nij->ni',Vr,gstf),axis=0))

    order=np.argsort(cells); counts=np.bincount(cells,minlength=NC); starts=np.r_[0,np.cumsum(counts)]
    for c in range(NC):
        idx=order[starts[c]:starts[c+1]]; m=len(idx)
        if m<2: continue
        Uc=v[idx].mean(0)
        expected=.5*m*(m-1)*WEIGHT*SIGMA_T*GMAJ*DT/VCELL
        nc=int(expected+rng.random()); nc=min(nc,m//2)
        if nc<1: continue
        ch=rng.choice(idx,size=2*nc,replace=False); ia=ch[:nc]; ib=ch[nc:]
        g=v[ia]-v[ib]; gn=np.linalg.norm(g,axis=1)
        if len(gn): max_g_seen=max(max_g_seen,float(np.max(gn)))
        majorant_hits += int(np.count_nonzero(gn>GMAJ))
        acc=rng.random(nc)<np.minimum(gn/GMAJ,1)
        if not np.any(acc): continue
        ia=ia[acc]; ib=ib[acc]; g=g[acc]; gn=gn[acc]; V=.5*(v[ia]+v[ib])
        sig=rng.normal(size=(len(ia),3)); sig/=np.linalg.norm(sig,axis=1)[:,None]; gp=gn[:,None]*sig
        vap=V+.5*gp; vbp=V-.5*gp
        if step>=BURN and c in cell_to_k:
            kk=cell_to_k[c]
            dP=.5*(gp[:,:,None]*gp[:,None,:]-g[:,:,None]*g[:,None,:]); tr=np.trace(dP,axis1=1,axis2=2); dP-=np.eye(3)[None,:,:]*(tr[:,None,None]/3)
            dQ=np.einsum('nj,nij->ni',V-Uc,dP)
            scale=WEIGHT/VCELL
            S_event[kk]+=scale*dP.sum(0); H_event[kk]+=scale*dQ.sum(0); n_event[kk]+=len(ia)
            bi=(step-BURN)//BLOCK; Sb[kk,bi]+=scale*dP.sum(0); Hb[kk,bi]+=scale*dQ.sum(0); Cb[kk,bi]+=len(ia)
        v[ia]=vap; v[ib]=vbp
    if (step+1)%3000==0: print(args.case,args.rep,step+1,'/',total,'elapsed',round(time.time()-start,1),flush=True)

# normalize event data
S_event/=SAMPLE_STEPS*DT; H_event/=SAMPLE_STEPS*DT
block_dur=np.minimum(BLOCK, SAMPLE_STEPS-np.arange(nb)*BLOCK)*DT
S_event_se=np.zeros_like(S_event); H_event_se=np.zeros_like(H_event)
for kk in range(nsamp):
    Sr=Sb[kk]/block_dur[:,None,None]; Hr=Hb[kk]/block_dur[:,None]
    S_event_se[kk]=Sr.std(axis=0,ddof=1)/math.sqrt(nb); H_event_se[kk]=Hr.std(axis=0,ddof=1)/math.sqrt(nb)

# profiles
nprof=np.divide(prof_n,prof_ct,out=np.zeros_like(prof_n),where=prof_ct>0)
uprof=np.divide(prof_u,prof_ct[:,None],out=np.zeros_like(prof_u),where=prof_ct[:,None]>0)
tprof=np.divide(prof_t,prof_ct,out=np.zeros_like(prof_t),where=prof_ct>0)

samples=[]
for kk,c in enumerate(SAMPLE_CELLS):
    ws=np.asarray(weakS[kk]); wh=np.asarray(weakH[kk]); A=np.asarray(snap_a[kk]); ns=np.asarray(snap_n[kk]); Ts=np.asarray(snap_T[kk])
    Sweak=ws.mean(0); Hweak=wh.mean(0)
    Sweak_se=ws.std(axis=0,ddof=1)/math.sqrt(len(ws)); Hweak_se=wh.std(axis=0,ddof=1)/math.sqrt(len(wh))
    Wstress=np.einsum('s,si,sj->ij',ns*ns*Ts**1.5,A,A)/len(A)
    Wheat=np.einsum('s,si,sj->ij',ns*ns*Ts**2.0,A,A)/len(A)
    recon={}
    for N in range(2,MAX_HERM+1):
        recon[str(N)]={'S':reconstruct_weighted(N,Wstress,False).tolist(),'H':reconstruct_weighted(N,Wheat,True).tolist()}
    samples.append({
      'cell':c,'y':(c+.5)*VCELL,'event_collisions':int(n_event[kk]),'snapshots':len(A),
      'S_event':S_event[kk].tolist(),'H_event':H_event[kk].tolist(),
      'S_event_se':S_event_se[kk].tolist(),'H_event_se':H_event_se[kk].tolist(),
      'S_weak':Sweak.tolist(),'H_weak':Hweak.tolist(),'S_weak_se':Sweak_se.tolist(),'H_weak_se':Hweak_se.tolist(),
      'reconstruction':recon,
      'local_mean_n':float(ns.mean()),'local_mean_T':float(Ts.mean()),
    })

out={'case':args.case,'rep':args.rep,'seed':SEED,'wall':pars,
     'params':{'NP':NP,'NC':NC,'dt':DT,'Kn':KN_TARGET,'diameter':DIAM,'n0':N0,'burn':BURN,'sample_steps':SAMPLE_STEPS,'stride':SNAP_STRIDE,'weak_pairs':WEAK_PAIRS,'max_herm':MAX_HERM,'sample_cells':SAMPLE_CELLS},
     'diagnostics':{'max_g_seen':max_g_seen,'majorant_hits':majorant_hits,'elapsed':time.time()-start},
     'profiles':{'y':((np.arange(NC)+.5)*VCELL).tolist(),'n':nprof.tolist(),'Ux':uprof[:,0].tolist(),'Uy':uprof[:,1].tolist(),'Uz':uprof[:,2].tolist(),'T':tprof.tolist()},
     'samples':samples}
with open(args.out,'w') as f: json.dump(out,f,indent=2)
print('DONE',args.out,'elapsed',round(out['diagnostics']['elapsed'],1),'maxg',round(max_g_seen,3),'hits',majorant_hits,flush=True)
